config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :series
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "series#index"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/series.rb
class Series < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: %i[ show edit update destroy ]

  # GET /series or /series.json
  def index
    @series = Series.all
  end

  # GET /series/1 or /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series or /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to series_url(@series), notice: "Series was successfully created." }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1 or /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to series_url(@series), notice: "Series was successfully updated." }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1 or /series/1.json
  def destroy
    @series.destroy

    respond_to do |format|
      format.html { redirect_to series_index_url, notice: "Series was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def series_params
      params.require(:series).permit(:nome, :situacao, :temporada, :plataforma)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeriesFlix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/series/_form.html.erb
<%= form_with(model: series) do |form| %>
  <% if series.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
        <% series.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :situacao, style: "display: block" %>
    <%= form.select :situacao, [["Para Assistir","Para Assistir"],["Em Andamento","Em Andamento"],["Concluída","Concluída"]], {include_blank:"Selecionar"},{class: "form-control"}%>
  </div>

  <div>
    <%= form.label :temporada, style: "display: block" %>
    <%= form.text_field :temporada %>
  </div>

  <div>
    <%= form.label :plataforma, style: "display: block" %>
    <%= form.select :plataforma, [["Amazon Prime","Amazon Prime"],["Crunchyroll","Crunchyroll"],["Disney+","Disney+"],["GlobPlay","GloboPlay"],["HBO MAX","HBO MAX"],["Netflix","Netflix"]], {include_blank:"Selecionar"},{class: "form-control"} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/series/_series.html.erb
<div id="<%= dom_id series %>">
  

  <div>
    <!--Definindo a classe table com bootstrap para renderizar em formato de tabela-->
    
    <table class="table table-dark table-striped align-middle">

    <thead>
      <tr>
        <th scope="col"></th>   
        <th scope="col">Situação</th>
        <th scope="col">Temporada</th>
        <th scope="col">Plataforma</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row"> <%= series.nome %> </th>
        <td><%= series.situacao %></td>
        <td><%= series.temporada %></td>
        <td><%= series.plataforma %></td>
      </tr>
    </tbody>
    </table>
  </div>

</div>

  

app/views/series/edit.html.erb
<h1>Editing series</h1>

<%= render "form", series: @series %>

<br>

<div>
  <%= link_to "Show this series", @series %> |
  <%= link_to "Back to series", series_index_path %>
</div>

app/views/series/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Series</h1>

<div id="series">
  <% @series.each do |series| %>
    <%= render series %>
    <p>
      <%= link_to "Show this series", series %>
    </p>
  <% end %>
</div>

<%= link_to "New series", new_series_path %>

<%= button_to "logout", destroy_user_session_path, method: :delete  %>

app/views/series/new.html.erb
<h1>New series</h1>

<%= render "form", series: @series %>

<br>

<div>
  <%= link_to "Back to series", series_index_path %>
</div>

app/views/series/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @series %>

<div>
  <%= link_to "Edit this series", edit_series_path(@series) %> |
  <%= link_to "Back to series", series_index_path %>

  <%= button_to "Destroy this series", @series, method: :delete %>
</div>